### PR TITLE
Login and Registration Tests

### PR DESCRIPTION
**Pull request by SivanMehta**
## What I did

In the process of creating `test/test-register.js` and `test/test-login.js` I also implemented a few new features a long the way including:

1. Use of HTTPS in local testing
2. Detailed instructions on how to set up the application in the README
3. Further use of the `config/api_wrapper.js` module for more streamlined code
4. Use of [`zombie.js`](http://zombie.js.org/) to walk through validating the login process

## Proof of Correctness

```

$ npm test
> ./SC-XW1
> mocha



 Forget Password
    ✓ should see the forget password (496ms)
    ✓ should not allow you to enter a invalid email (859ms)
    ✓ should allow you to enter a valid email and confirm a sent email (1162ms)
    ✓ should tell you if you aren't recognized by the server (1218ms)

 SC Server
    ✓ should accept valid login credentials (96ms)
    ✓ should not accept invalid login credentials (59ms)

  Walking through the login process
    ✓ should have defined headless browser
    ✓ should visit the site and see the login form (610ms)
    ✓ should not be able to login with wrong credentials (558ms)
    ✓ should be able to login with valid credentials (1932ms)

  Looking through receipts
    ✓ should have defined headless browser and log in  (518ms)
    ✓ should be able to login with valid credentials (1589ms)
    ✓ should navigate to the receipts page and see the Home Depot (771ms)
    ✓ should be able to click on a receipt to see its information
    ✓ should be able to see the original HTML page
    ✓ should be able to go to the popped out receipt page (4911ms)
    ✓ should be able to see the Google Map

  /routes/routes.js
    register(req, res)
      ✓ should be able to be able to register a new user (93ms)
      ✓ should be able to login as the newly created user (72ms)

  /routes/validate.js
    isEmail(str)
      ✓ should allow valid emails
      ✓ should not allow invalid emails
    new_user(body)
      ✓ should not allow an invalid email
      ✓ should not allow an invalid username
      ✓ should not allow an invalid password
      ✓ should allow an valid body object


  23 passing (15s)
```

### CODE REVIEW

**Comment by ziyunzamy** [comment]
good documentation in the set up part, we might need to put more testing instruction into readme
I followed the steps from the README, run the commend like this:

`Ziyuns-MBP-3:SC-XW1 ziyunzheng$ openssl req -nodes -x509 -newkey rsa:2048 -keyout config/key.pem -out config/cert.pem -days 365`

I successfully started out the server, but Chorme warned me about some safety issues and in the url it crossed out the HTTPS for me, is that what supposed to happen if we run the code locally?

Other than that, I run the test successfully, and caught the register user API is not responding correctly, which means our test works!! YAY!

**Comment by SivanMehta** [comment]
The crossed out HTTPS sign means that it doesn't recognize the certificate, which is completely fine because we signed it ourselves. You can learn more about certificates [here](https://www.instantssl.com/ssl-certificate-products/https.html). If you go to swiftceipt.com, you will see that their one is OK for the following reason:

> COMODO RSA Domain Validation Secure Server CA issued this website's certificate

**Comment by ziyunzamy** [comment]
i saw the additional changes that you made, what is that "test@ceet.us" thing in the nav bar?

**Comment by SivanMehta** [comment]
@ziyunzamy I remembered that Jon noted he wanted that done, I just did it here because we had forgot it previously

**Pull request merged**
